config/routes.rb
Rails.application.routes.draw do
  resources :comments 
  resources :categories do
    resources :links
  end
  devise_for :users
  resources :links do
    resources :comments
  end

  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :links
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @links = Link.where({category_id: @category.id})
    session[:temp_category] = @category.id
    redirect_to links_url
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @categories = Category.all
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  #def show
  #end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      @link = Link.find(params[:link_id])
      @comment = @link.comments.new(comment_params)
      @comment.user = current_user
      if @comment.update(comment_params)
        format.html { redirect_to @link, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  $category_id = nil
  # GET /links
  # GET /links.json
  def index
    if !session[:temp_category].nil?
      $category_id  = session[:temp_category]
      @category = Category.find_by({id: $category_id})
    end
    if Link.exists?(category_id: $category_id)
      @links = Link.where({category_id: $category_id})
      @category = Category.find_by({id: $category_id})
    end
    session[:temp_category] = nil
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @category = Category.find_by({id: $category_id})
    puts @category
  end

  # GET /links/new
  def new
    c_id = params[:category_id]
    puts "c_id is" + params[:category_id].to_s
    session[:temp_c] = c_id
    @link = Link.new(category_id: c_id)
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    c_id = params[:c_id]
    @link = current_user.links.build(link_params)
    @link.category_id = c_id
    session[:temp_c] = nil
    puts "category_id" + @link.category_id.to_s
    respond_to do |format|
      if @link.save
        session[:temp_category] = @link.category_id
        format.html { redirect_to action: "index", notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :content, :category_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit",  class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course List</h1>
    <% @categories.each do |category| %>
      <div class="link row clearfix">
        <div class="actual_content">
        <h2> <%= link_to category.name, category %></h2></br>
        </div>
        <% if current_user != category.user %>
        <div class="btn-group">
          <%= link_to 'Edit', edit_category_path(category), class: "btn btn-default btn-small"%>
          <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
        </div>
      <% end %>
      </div>
    <% end %>
 <%= link_to 'New Course', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by</small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user %>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-defualt" %>
			<% end %>
		</div>
	</div>
<% end %>  

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit, class: "btn btn-lg btn-primary"  %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment. %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>:</strong>
  <%= @comment.id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubjectV11</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
	<% content_tag(:div, msg, class: "alert alert ~%(name)") %>
<% end %>

<header>
<div class="header container">
	<h1><%= link_to "Subject Helper", root_url %></h1>
	<nav> 
		<% if user_signed_in? %>
			<ul>
				<li><%= link_to "Account", edit_user_registration_path %></li>
				<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
			</ul>
		<% else %>
			<ul>
				<li><%= link_to "Log in", new_user_session_path %></li>
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
			</ul>
		<% end %>
	</nav>
</div>
</header>	

<div id="main_content" class="container">
	<% flash.each do |name, msg| %>
			<% content_tag(:div, msg, class: "alert alert~%(name)") %>
	<% end %>
	<div id="content">
		<%= yield %> 
	</div>
</div>


</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>


<table>
  <h2 class="sub_title"><%= @category.name  %></h2><br/>
  <%= link_to 'New Link', new_link_path(:category_id =>  @c_id) %>
  <% if !@links.nil? %>
      <% @links.each do |link| %>
        <div class="link row clearfix">
           <div class="actual_content">
            <h2><%= link_to link.title, link %></h2>
              <div class="content-info">
                <small class="author">Submitted by <%= link.user.email %></small>
              <% if link.user == current_user %>
              <div class="btn-group">
                <%= link_to 'Edit', edit_link_path(link), class: "btn btn-default btn-small" %>
                <%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"%>
              </div>
              <% end %>
              </div>
          </div>
        </div>
      <% end %>
    <% else %>
        <h2>Create a new post</h2>
      
    </tbody>
  <% end %>
</table>

<br>
<h3><%= @c_id %></h3>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="sub_title"><%= @category.name  %></h2><br/>
<div class="link row clearfix">
    <h2>
      <%= @link.title %></br>
      <div class="content-info">
        <small class="subject"><%= @link.content %></small></br>
        <small class="author"> <strong><%= time_ago_in_words(@link.created_at) %></strong> ago</strong> by </small>

      </div>
    </h2>
    <% if @link.user == current_user %>
		<div class="btn-group">
			<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
			<%= link_to "Destroy", @link, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-defualt" %>
		</div>
	<% end %>
	</div>
	<hr>

<h3>
  <%= @link.comments.count %>Comments
</h3>
<div id="comments">
	<%= render :partial => @link.comments %>
</div>
<%= simple_form_for [@link, Comment.new] do |f| %>
	<div class="field">
		<%= f.text_area :body, class: "form-control" %>
	</div>
	<br>
	<%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>
<%= link_to 'Back', links_path %>